export type Category = 'Training' | 'Hardware' | 'Setup';

export const tools = [
  {
    id: 'aim',
    name: 'Aim trainer',
    description: 'Build precision. Find your rhythm. Make every shot count.',
    category: 'Training',
    icon: 'crosshair',
    color: 'violet',
    tag: 'FAN FAVORITE',
    detail: '15–60 sec · 3D range',
  },
  {
    id: 'reaction',
    name: 'Reaction time',
    description: 'How fast are your reflexes? Put them to the test.',
    category: 'Training',
    icon: 'zap',
    color: 'amber',
    tag: 'QUICK PLAY',
    detail: '5-round challenge',
  },
  {
    id: 'keyboard',
    name: 'Keyboard tester',
    description: 'Every key, every press. Make sure nothing holds you back.',
    category: 'Hardware',
    icon: 'keyboard',
    color: 'blue',
    tag: '',
    detail: 'Live key detection',
  },
  {
    id: 'mouse',
    name: 'Mouse tester',
    description: 'Check your clicks, scroll wheel, and pointer movement.',
    category: 'Hardware',
    icon: 'mouse',
    color: 'pink',
    tag: '',
    detail: 'Buttons & tracking',
  },
  {
    id: 'display',
    name: 'Display tester',
    description: 'Inspect your panel, explore color and motion, and check frame pacing.',
    category: 'Hardware',
    icon: 'monitor',
    color: 'mint',
    tag: '',
    detail: '12 guided display checks',
  },
  {
    id: 'sensitivity',
    name: 'Sensitivity calculator',
    description: 'New DPI, same muscle memory. Dial in your setup.',
    category: 'Setup',
    icon: 'sliders',
    color: 'violet',
    tag: 'ESSENTIAL',
    detail: 'DPI & eDPI',
  },
  {
    id: 'cps',
    name: 'Click speed',
    description: 'Find your clicking rhythm with a five-second sprint.',
    category: 'Training',
    icon: 'click',
    color: 'pink',
    tag: '',
    detail: '5-second challenge',
  },
  {
    id: 'gamepad',
    name: 'Gamepad tester',
    description: 'Check button inputs, triggers, and thumbstick drift.',
    category: 'Hardware',
    icon: 'gamepad',
    color: 'blue',
    tag: '',
    detail: 'Live controller inputs',
  },
  {
    id: 'crosshair',
    name: 'Crosshair studio',
    description: 'Create your signature crosshair. Preview and export it.',
    category: 'Setup',
    icon: 'focus',
    color: 'mint',
    tag: 'GET CREATIVE',
    detail: 'Custom PNG export',
  },
  {
    id: 'audio',
    name: 'Microphone test',
    description: 'Check your mic levels before you join the squad.',
    category: 'Hardware',
    icon: 'mic',
    color: 'amber',
    tag: '',
    detail: 'Live input levels',
  },
  {
    id: 'webcam',
    name: 'Webcam test',
    description: 'Preview your camera and get ready for your next stream.',
    category: 'Hardware',
    icon: 'video',
    color: 'pink',
    tag: '',
    detail: 'Preview & snapshots',
  },
  {
    id: 'session',
    name: 'Session timer',
    description: 'Play with focus. Make time to reset between matches.',
    category: 'Setup',
    icon: 'timer',
    color: 'violet',
    tag: '',
    detail: 'Focus & break timer',
  },
] as const;

export type ToolId = (typeof tools)[number]['id'];
export type Tool = (typeof tools)[number];
export const findTool = (id: string) => tools.find((tool) => tool.id === id);

export const guides = [
  {
    id: 'warmup',
    title: 'Your 5-minute pre-game warm-up',
    subtitle: 'Small routine. Better first match.',
    category: 'PLAY SMARTER',
    icon: 'crosshair',
    color: 'violet',
    minutes: 3,
    paragraphs: [
      [
        'Start with your setup',
        'Sit comfortably, clear your mouse space, and check that your sensitivity matches your usual settings. A consistent setup makes your practice easier to compare.',
      ],
      [
        'Get into a rhythm',
        'Spend a minute on the reaction test, then a couple of minutes in the aim trainer. Start with accurate clicks and increase your pace gradually. Take a short pause between attempts.',
      ],
      [
        'Keep the goal simple',
        'Focus on one thing for your next match: calm crosshair placement, better movement, or clearer communication. These browser drills are a warm-up; practice inside your game matters too.',
      ],
    ],
    tool: 'aim',
  },
  {
    id: 'gear',
    title: 'Is your gear game-ready?',
    subtitle: 'A quick check before you queue.',
    category: 'KNOW YOUR GEAR',
    icon: 'keyboard',
    color: 'blue',
    minutes: 4,
    paragraphs: [
      [
        'Check the basics',
        'Use the keyboard tester to check your movement keys and common shortcuts. Press combinations you actually use in a match. Some system shortcuts are intercepted by your operating system and never reach a browser.',
      ],
      [
        'Clicks, sticks, and screens',
        'Check your mouse buttons or connect a controller and inspect the sticks at rest. Use the display tester to look for unusual pixels. Browser measurements describe events available to the page; they cannot certify hardware latency or polling rates.',
      ],
      [
        'Test your comms',
        'Start a microphone check and speak at your usual distance. If levels stay near the top, lower your input gain. Preview your camera if you stream, and stop both devices when you finish.',
      ],
    ],
    tool: 'keyboard',
  },
  {
    id: 'sensitivity',
    title: 'Find your sensitivity sweet spot',
    subtitle: 'Consistency starts with your settings.',
    category: 'DIAL IT IN',
    icon: 'sliders',
    color: 'mint',
    minutes: 3,
    paragraphs: [
      [
        'Understand eDPI',
        'Effective DPI is your mouse DPI multiplied by your in-game sensitivity. It helps compare settings within the same game and sensitivity scale. It does not directly compare different games.',
      ],
      [
        'Changing your mouse DPI',
        'To preserve your turn distance in the same game, multiply your current sensitivity by your old DPI, then divide by your new DPI. Our calculator does the arithmetic for you.',
      ],
      [
        'Change one thing at a time',
        'Try small adjustments, play a few practice rounds, and keep notes. A comfortable sensitivity that you can use consistently is more useful than copying someone else’s settings.',
      ],
    ],
    tool: 'sensitivity',
  },
] as const;
